/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class twentyone extends javax.swing.JFrame {

    /** Creates new form twentyone */
    public twentyone() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        buttonGroup21 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rb26 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb16 = new javax.swing.JRadioButton();
        rb27 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb17 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        rb28 = new javax.swing.JRadioButton();
        rb29 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb30 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        rb18 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        rb5 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rb31 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        rb32 = new javax.swing.JRadioButton();
        rb19 = new javax.swing.JRadioButton();
        rb33 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb34 = new javax.swing.JRadioButton();
        rb20 = new javax.swing.JRadioButton();
        rb35 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb36 = new javax.swing.JRadioButton();
        rb21 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rb8 = new javax.swing.JRadioButton();
        rb37 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rb22 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rb9 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rb38 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        rb39 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rb23 = new javax.swing.JRadioButton();
        rb40 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rb10 = new javax.swing.JRadioButton();
        rb41 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rb42 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rb11 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rb25 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("Day 6 having any symptoms?");

        jLabel8.setText("Day 7 having any symptoms?");

        rb26.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup12.add(rb26);
        rb26.setText("No");
        rb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb26ActionPerformed(evt);
            }
        });

        rb13.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup13.add(rb13);
        rb13.setText("Yes");

        rb16.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(rb16);
        rb16.setText("No");

        rb27.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup13.add(rb27);
        rb27.setText("No");

        rb3.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(rb3);
        rb3.setText("Yes");

        rb17.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(rb17);
        rb17.setText("No");

        rb14.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup14.add(rb14);
        rb14.setText("Yes");

        rb28.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup14.add(rb28);
        rb28.setText("No");

        rb29.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup15.add(rb29);
        rb29.setText("Yes");
        rb29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb29ActionPerformed(evt);
            }
        });

        rb4.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup4.add(rb4);
        rb4.setText("Yes");

        rb30.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup16.add(rb30);
        rb30.setText("Yes");
        rb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb30ActionPerformed(evt);
            }
        });

        jButton2.setText("DONE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rb18.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup4.add(rb18);
        rb18.setText("No");

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rb5.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup5.add(rb5);
        rb5.setText("Yes");

        jLabel16.setText("Day 15 having any symptoms?");

        rb31.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup17.add(rb31);
        rb31.setText("Yes");
        rb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb31ActionPerformed(evt);
            }
        });

        jLabel17.setText("Day 16 having any symptoms?");

        rb32.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup18.add(rb32);
        rb32.setText("Yes");
        rb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb32ActionPerformed(evt);
            }
        });

        rb19.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup5.add(rb19);
        rb19.setText("No");

        rb33.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup19.add(rb33);
        rb33.setText("Yes");
        rb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb33ActionPerformed(evt);
            }
        });

        rb6.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup6.add(rb6);
        rb6.setText("Yes");

        rb34.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup20.add(rb34);
        rb34.setText("Yes");

        rb20.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup6.add(rb20);
        rb20.setText("No");

        rb35.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup21.add(rb35);
        rb35.setText("Yes");

        rb7.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup7.add(rb7);
        rb7.setText("Yes");

        rb36.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup15.add(rb36);
        rb36.setText("No");

        rb21.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup7.add(rb21);
        rb21.setText("No");

        jLabel18.setText("Day 17 having any symptoms?");

        rb8.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup8.add(rb8);
        rb8.setText("Yes");
        rb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8ActionPerformed(evt);
            }
        });

        rb37.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup16.add(rb37);
        rb37.setText("No");
        rb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb37ActionPerformed(evt);
            }
        });

        jLabel9.setText("Day 8 having any symptoms?");

        rb22.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup8.add(rb22);
        rb22.setText("No");
        rb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb22ActionPerformed(evt);
            }
        });

        jLabel10.setText("Day 9 having any symptoms?");

        rb9.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup9.add(rb9);
        rb9.setText("Yes");
        rb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb9ActionPerformed(evt);
            }
        });

        jLabel19.setText("Day 18 having any symptoms?");

        rb38.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup17.add(rb38);
        rb38.setText("No");
        rb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb38ActionPerformed(evt);
            }
        });

        jLabel20.setText("Day 19 having any symptoms?");

        rb39.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup18.add(rb39);
        rb39.setText("No");

        jLabel11.setText("Day 10 having any symptoms?");

        jLabel21.setText("Day 20 having any symptoms?");

        rb23.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup9.add(rb23);
        rb23.setText("No");
        rb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb23ActionPerformed(evt);
            }
        });

        rb40.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup19.add(rb40);
        rb40.setText("No");

        jLabel12.setText("Day 11 having any symptoms?");

        jLabel22.setText("Day 21 having any symptoms?");

        rb10.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup10.add(rb10);
        rb10.setText("Yes");
        rb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb10ActionPerformed(evt);
            }
        });

        rb41.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup20.add(rb41);
        rb41.setText("No");
        rb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb41ActionPerformed(evt);
            }
        });

        jLabel13.setText("Day 12 having any symptoms?");

        rb42.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup21.add(rb42);
        rb42.setText("No");
        rb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb42ActionPerformed(evt);
            }
        });

        rb24.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup10.add(rb24);
        rb24.setText("No");

        jLabel14.setText("Day 13 having any symptoms?");

        rb11.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup11.add(rb11);
        rb11.setText("Yes");

        jLabel15.setText("Day 14 having any symptoms?");

        rb25.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup11.add(rb25);
        rb25.setText("No");

        rb1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rb1);
        rb1.setText("Yes");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb12.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup12.add(rb12);
        rb12.setText("Yes");

        rb15.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rb15);
        rb15.setText("No");

        rb2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(rb2);
        rb2.setText("Yes");

        jLabel1.setText("PLEASE ANSWER THE FOLLOWING QUESTIONS:");

        jLabel2.setText("Day 1 having any symptoms?");

        jLabel3.setText("Day 2 having any symptoms?");

        jLabel4.setText("Day 3 having any symptoms?");

        jLabel5.setText("Day 4 having any symptoms?");

        jLabel6.setText("Day 5 having any symptoms?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel15)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rb31, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rb30, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rb38)
                                        .addComponent(rb37)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb42))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb36))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(rb14)
                                                    .addComponent(rb13)
                                                    .addComponent(rb12)
                                                    .addComponent(rb11)
                                                    .addComponent(rb10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rb24)
                                                    .addComponent(rb25)
                                                    .addComponent(rb26)
                                                    .addComponent(rb27)
                                                    .addComponent(rb28)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rb9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb23))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rb8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb22)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rb2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb16))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rb3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb17))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rb4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rb7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb21))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(rb6, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rb5, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rb19)
                                                .addComponent(rb20)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rb1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb15)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rb34)
                                                .addComponent(rb32, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(rb33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb40)
                                            .addComponent(rb41)
                                            .addComponent(rb39)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rb1)
                    .addComponent(rb15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rb2)
                    .addComponent(rb16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb3)
                    .addComponent(rb17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb4)
                    .addComponent(rb18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb5)
                    .addComponent(rb19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rb6)
                    .addComponent(rb20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rb7)
                    .addComponent(rb21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb8)
                    .addComponent(rb22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rb9)
                    .addComponent(rb23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rb10)
                    .addComponent(rb24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rb11)
                    .addComponent(rb25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rb12)
                    .addComponent(rb26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rb13)
                    .addComponent(rb27))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rb14)
                    .addComponent(rb28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(rb29)
                    .addComponent(rb36))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rb37)
                    .addComponent(rb30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rb31)
                    .addComponent(rb38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rb32)
                    .addComponent(rb39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb33)
                        .addComponent(rb40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(rb34)
                    .addComponent(rb41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rb35)
                    .addComponent(rb42))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code h
        int wan=0;
        int tu=0;

        if(rb1.isSelected()){
            wan += 1;
        }
        if (rb2.isSelected()){
            wan += 1;
        }
        if (rb3.isSelected()){
            wan += 1;
        }
        if (rb4.isSelected()){
            wan += 1;
        }
        if (rb5.isSelected()){
            wan += 1;
        }
        if (rb6.isSelected()){
            wan += 1;
        }
        if (rb7.isSelected()){
            wan += 1;
        }
        if (rb8.isSelected()){
            wan += 1;
        }
        if (rb9.isSelected()){
            wan += 1;
        }
        if (rb10.isSelected()){
            wan += 1;
        }
        if (rb11.isSelected()){
            wan += 1;
        }
        if (rb12.isSelected()){
            wan += 1;
        }
        if (rb13.isSelected()){
            wan += 1;
        }
        if (rb14.isSelected()){
            wan += 1;
        }
        if (rb29.isSelected()){
            wan += 1;
        }
        if (rb30.isSelected()){
            wan += 1;
        }
        if (rb31.isSelected()){
            wan += 1;
        }
        if (rb32.isSelected()){
            wan += 1;
        }
        if (rb33.isSelected()){
            wan += 1;
        }
        if (rb34.isSelected()){
            wan += 1;
        }
        if (rb35.isSelected()){
            wan += 1;
        }
        if(rb15.isSelected()){
            tu += 1;
        }
        if (rb16.isSelected()){
            tu += 1;
        }
        if (rb17.isSelected()){
            tu += 1;
        }
        if (rb18.isSelected()){
            tu += 1;
        }
        if (rb19.isSelected()){
            tu += 1;
        }
        if (rb20.isSelected()){
            tu += 1;
        }
        if (rb21.isSelected()){
            tu += 1;
        }
        if (rb22.isSelected()){
            tu += 1;
        }
        if (rb23.isSelected()){
            tu += 1;
        }
        if (rb24.isSelected()){
            tu += 1;
        }
        if (rb25.isSelected()){
            tu += 1;
        }
        if (rb26.isSelected()){
            tu += 1;
        }
        if (rb27.isSelected()){
            tu += 1;
        }
        if (rb28.isSelected()){
            tu += 1;
        }
        if (rb36.isSelected()){
            tu += 1;
        }
        if (rb37.isSelected()){
            tu += 1;
        }
        if (rb38.isSelected()){
            tu += 1;
        }
        if (rb39.isSelected()){
            tu += 1;
        }
        if (rb40.isSelected()){
            tu += 1;
        }
        if (rb41.isSelected()){
            tu += 1;
        }
        if (rb42.isSelected()){
            tu += 1;
        }
        

        switch (wan){
            case 1:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 2:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 3:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 4:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 5:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 6:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 7:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 8:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 9:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 10:
            JOptionPane.showMessageDialog(this, "Case Category: Mild Case!");
            break;
            case 11:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 12:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 13:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 14:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 15:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 16:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 17:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 18:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 19:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 20:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
            case 21:
            JOptionPane.showMessageDialog(this, "Case Category: Severe Case!");
            break;
        }
        switch (tu){
            case 21:
            JOptionPane.showMessageDialog(this, "Case Category: Asymptomatic!");
            break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        second fr = new second();
        fr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb8ActionPerformed

    private void rb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb22ActionPerformed

    private void rb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb9ActionPerformed

    private void rb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb23ActionPerformed

    private void rb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb10ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb26ActionPerformed

    private void rb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb30ActionPerformed

    private void rb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb31ActionPerformed

    private void rb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb32ActionPerformed

    private void rb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb33ActionPerformed

    private void rb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb37ActionPerformed

    private void rb38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb38ActionPerformed

    private void rb29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb29ActionPerformed

    private void rb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb41ActionPerformed

    private void rb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb42ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(twentyone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(twentyone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(twentyone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(twentyone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new twentyone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup21;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JRadioButton rb17;
    private javax.swing.JRadioButton rb18;
    private javax.swing.JRadioButton rb19;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb20;
    private javax.swing.JRadioButton rb21;
    private javax.swing.JRadioButton rb22;
    private javax.swing.JRadioButton rb23;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rb25;
    private javax.swing.JRadioButton rb26;
    private javax.swing.JRadioButton rb27;
    private javax.swing.JRadioButton rb28;
    private javax.swing.JRadioButton rb29;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb30;
    private javax.swing.JRadioButton rb31;
    private javax.swing.JRadioButton rb32;
    private javax.swing.JRadioButton rb33;
    private javax.swing.JRadioButton rb34;
    private javax.swing.JRadioButton rb35;
    private javax.swing.JRadioButton rb36;
    private javax.swing.JRadioButton rb37;
    private javax.swing.JRadioButton rb38;
    private javax.swing.JRadioButton rb39;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb40;
    private javax.swing.JRadioButton rb41;
    private javax.swing.JRadioButton rb42;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    // End of variables declaration//GEN-END:variables

}
